// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzoskeloofwnnderotmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6b3NrZWxvb2Z3bm5kZXJvdG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDE5ODEsImV4cCI6MjA3MzYxNzk4MX0.WIF_w2jrcuNczXUcmvh78rMYUabS-wp210zOd0WPanY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});